# Generated by Django 5.0.6 on 2026-07-02 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
        ("tenants", "0008_rename_globaldefaultbelt_belt_alter_belt_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classtype",
            name="min_belt_rank",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="minimum_class_types",
                to="tenants.belt",
            ),
        ),
    ]
