# Generated by Django 5.0.6 on 2026-07-02 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_classtype_min_belt_rank'),
        ('belts', '0004_belt_alter_promotioneligibility_next_belt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtype',
            name='min_belt_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minimum_class_types', to='belts.belt'),
        ),
    ]
