# Generated by Django 5.0.6 on 2026-07-09 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayrollRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft (مسودة)"),
                            ("approved", "Approved (معتمد)"),
                            ("paid", "Paid (مدفوع)"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Payroll Run",
                "verbose_name_plural": "Payroll Runs",
                "ordering": ["-year", "-month"],
                "unique_together": {("year", "month")},
            },
        ),
        migrations.CreateModel(
            name="StaffDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="staff_documents/%Y/%m/")),
                ("notes", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "staff_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="staff.staffmember",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Document",
                "verbose_name_plural": "Staff Documents",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="StaffSalaryConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Monthly Fixed (راتب شهري ثابت)"),
                            ("part_time", "Hourly Rate (أجر بالساعة)"),
                            ("session_based", "Session Rate (أجر بالحصة)"),
                        ],
                        default="full_time",
                        max_length=20,
                    ),
                ),
                (
                    "basic_salary",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="الراتب الأساسي الشهري",
                        max_digits=10,
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="سعر ساعة العمل للموظفين بالساعة",
                        max_digits=10,
                    ),
                ),
                (
                    "session_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="سعر الحصة/الكلاس للمدربين بالحصة",
                        max_digits=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("JOD", "دينار أردني (JOD)"),
                            ("SAR", "ريال سعودي (SAR)"),
                            ("AED", "درهم إماراتي (AED)"),
                            ("KWD", "دينار كويتي (KWD)"),
                            ("BHD", "دينار بحريني (BHD)"),
                            ("OMR", "ريال عماني (OMR)"),
                            ("QAR", "ريال قطري (QAR)"),
                            ("EGP", "جنيه مصري (EGP)"),
                            ("USD", "دولار أمريكي (USD)"),
                        ],
                        default="JOD",
                        max_length=3,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "staff_member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_config",
                        to="staff.staffmember",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Salary Configuration",
                "verbose_name_plural": "Staff Salary Configurations",
            },
        ),
        migrations.CreateModel(
            name="StaffPayslip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Monthly Fixed (راتب شهري ثابت)"),
                            ("part_time", "Hourly Rate (أجر بالساعة)"),
                            ("session_based", "Session Rate (أجر بالحصة)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "basic_salary",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "calculated_units",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="عدد الساعات أو الحصص المنجزة",
                        max_digits=10,
                    ),
                ),
                (
                    "unit_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="أجر الساعة أو الحصة",
                        max_digits=10,
                    ),
                ),
                (
                    "allowances",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="علاوات وإضافات",
                        max_digits=10,
                    ),
                ),
                (
                    "deductions",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="خصومات واستقطاعات",
                        max_digits=10,
                    ),
                ),
                (
                    "net_salary",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending (معلق)"),
                            ("paid", "Paid (مدفوع)"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payment_date", models.DateField(blank=True, null=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash (نقداً)"),
                            ("bank_transfer", "Bank Transfer (تحويل بنكي)"),
                            ("check", "Check (شيك)"),
                            ("other", "Other (أخرى)"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payroll_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to="staff.payrollrun",
                    ),
                ),
                (
                    "staff_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payslips",
                        to="staff.staffmember",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Payslip",
                "verbose_name_plural": "Staff Payslips",
                "unique_together": {("payroll_run", "staff_member")},
            },
        ),
    ]
