# Generated by Django 5.0.6 on 2026-04-25 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("renewal_reminder", "Renewal Reminder"),
                            ("overdue_notice", "Overdue Payment Notice"),
                            ("welcome", "Welcome Message"),
                            ("promotion_alert", "Belt Promotion Alert"),
                            ("trial_followup", "Trial Follow-up"),
                            ("broadcast", "Broadcast Announcement"),
                            ("class_reminder", "Class Reminder"),
                            ("birthday", "Birthday Message"),
                        ],
                        max_length=30,
                    ),
                ),
                ("language", models.CharField(default="ar", max_length=5)),
                ("subject", models.CharField(blank=True, max_length=200)),
                (
                    "body_template",
                    models.TextField(
                        help_text="Use {student_name}, {amount}, {due_date}, {location_name} etc."
                    ),
                ),
                (
                    "whatsapp_template_name",
                    models.CharField(blank=True, max_length=200),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("template_type", "language")},
            },
        ),
        migrations.CreateModel(
            name="BroadcastCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                            ("in_app", "In-App"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "audience_filter",
                    models.JSONField(
                        default=dict,
                        help_text="JSON filter: {status: 'active', location_id: 1, belt_rank: 'white'}",
                    ),
                ),
                ("estimated_recipients", models.PositiveIntegerField(default=0)),
                ("actual_recipients", models.PositiveIntegerField(default=0)),
                ("sent_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("scheduled_for", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_by_id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="messaging.messagetemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient_phone", models.CharField(blank=True, max_length=30)),
                ("recipient_email", models.EmailField(blank=True, max_length=254)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("push", "Push Notification"),
                            ("in_app", "In-App"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("content", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("read", "Read"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("provider_response", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("triggered_by_id", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="students.student",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="messaging.messagetemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="messaging_n_status_8fcdd5_idx"
                    ),
                    models.Index(
                        fields=["student", "channel"],
                        name="messaging_n_student_b11cd3_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="messaging_n_created_9062e3_idx"
                    ),
                ],
            },
        ),
    ]
