# Generated by Django 5.0.6 on 2026-04-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="broadcastcampaign",
            name="audience_filter",
            field=models.JSONField(
                default=dict,
                help_text='JSON filter: {"status": "active", "location_id": 1, "belt_rank": "white"}',
            ),
        ),
    ]
