# Generated by Django 5.0.6 on 2026-05-10 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BeltRank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("martial_art", models.CharField(default="General", max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("name_ar", models.CharField(blank=True, max_length=100)),
                ("color_hex", models.CharField(default="#FFFFFF", max_length=7)),
                ("order_index", models.PositiveIntegerField(default=0)),
                ("min_attendance_sessions", models.PositiveIntegerField(default=0)),
                ("min_months_since_last", models.PositiveIntegerField(default=0)),
                ("min_age", models.PositiveIntegerField(blank=True, null=True)),
                ("max_age", models.PositiveIntegerField(blank=True, null=True)),
                ("requires_exam", models.BooleanField(default=False)),
                (
                    "exam_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["martial_art", "order_index"],
                "unique_together": {("martial_art", "order_index")},
            },
        ),
        migrations.CreateModel(
            name="PromotionEligibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sessions_completed", models.PositiveIntegerField(default=0)),
                ("sessions_required", models.PositiveIntegerField(default=0)),
                ("months_since_last", models.PositiveIntegerField(default=0)),
                ("is_eligible", models.BooleanField(default=False)),
                ("alert_sent", models.BooleanField(default=False)),
                ("checked_at", models.DateTimeField(auto_now=True)),
                (
                    "next_belt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="belts.beltrank",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_eligibility",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Promotion Eligibilities",
            },
        ),
        migrations.CreateModel(
            name="StudentBelt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("promoted_at", models.DateField()),
                ("promoted_by_id", models.UUIDField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=True)),
                ("attendance_at_promotion", models.PositiveIntegerField(default=0)),
                ("certificate_url", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "belt_rank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="promotions",
                        to="belts.beltrank",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="belt_history",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-promoted_at"],
                "indexes": [
                    models.Index(
                        fields=["student", "is_current"],
                        name="belts_stude_student_ae4607_idx",
                    )
                ],
            },
        ),
    ]
