# Generated by Django 5.0.6 on 2026-07-02 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belts", "0001_initial"),
        ("attendance", "0002_alter_classtype_min_belt_rank"),
        ("tenants", "0008_rename_globaldefaultbelt_belt_alter_belt_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotioneligibility",
            name="next_belt",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tenants.belt",
            ),
        ),
        migrations.AlterField(
            model_name="studentbelt",
            name="belt_rank",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="promotions",
                to="tenants.belt",
            ),
        ),
        migrations.DeleteModel(
            name="BeltRank",
        ),
    ]
