# Generated by Django 5.0.6 on 2026-07-02 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
        ("belts", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BeltRank",
        ),
    ]
