# Generated by Django 5.0.6 on 2026-04-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentbelt",
            name="promoted_by_id",
        ),
        migrations.AddField(
            model_name="studentbelt",
            name="promoted_by_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
