# Generated by Django 5.0.6 on 2026-07-02 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("belts", "0002_delete_beltrank"),
    ]

    operations = [
    ]
