# Generated by Django 5.0.6 on 2026-07-02 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belts', '0003_alter_promotioneligibility_next_belt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Belt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('martial_art', models.CharField(default='BJJ', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('name_ar', models.CharField(blank=True, max_length=100)),
                ('color_hex', models.CharField(default='#FFFFFF', max_length=7)),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('min_attendance_sessions', models.PositiveIntegerField(default=0)),
                ('min_months_since_last', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Belt',
                'verbose_name_plural': 'Belts',
                'ordering': ['martial_art', 'order_index'],
            },
        ),
        migrations.AlterField(
            model_name='promotioneligibility',
            name='next_belt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='belts.belt'),
        ),
        migrations.AlterField(
            model_name='studentbelt',
            name='belt_rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='belts.belt'),
        ),
    ]
