# Generated by Django 5.0.6 on 2026-07-10 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belts", "0004_belt_alter_promotioneligibility_next_belt_and_more"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BeltExam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("date", models.DateField()),
                ("martial_art", models.CharField(default="BJJ", max_length=100)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="belt_exams",
                        to="students.location",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExamCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("technical_grade", models.CharField(blank=True, max_length=10)),
                ("instructor_notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Evaluation"),
                            ("passed", "Passed & Promoted"),
                            ("failed", "Retry Recommended"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("graded_by_id", models.UUIDField(blank=True, null=True)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="belts.beltexam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_candidacies",
                        to="students.student",
                    ),
                ),
                (
                    "target_belt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exam_candidates",
                        to="belts.belt",
                    ),
                ),
            ],
            options={
                "ordering": ["student__first_name", "student__last_name"],
                "unique_together": {("exam", "student")},
            },
        ),
    ]
