# Generated by Django 5.0.6 on 2026-07-10 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("belts", "0005_beltexam_examcandidate"),
        ("billing", "0002_alter_invoice_currency_alter_membershipplan_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="beltexam",
            name="auto_create_invoice",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="beltexam",
            name="registration_fee",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="examcandidate",
            name="double_promotion_belt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="double_promoted_candidates",
                to="belts.belt",
            ),
        ),
        migrations.AddField(
            model_name="examcandidate",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="exam_candidates",
                to="billing.invoice",
            ),
        ),
        migrations.CreateModel(
            name="BeltSyllabusRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("name_ar", models.CharField(blank=True, max_length=200)),
                ("max_score", models.PositiveIntegerField(default=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "belt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="syllabus_requirements",
                        to="belts.belt",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="CandidateSyllabusGrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveIntegerField(default=0)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="syllabus_grades",
                        to="belts.examcandidate",
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grades",
                        to="belts.beltsyllabusrequirement",
                    ),
                ),
            ],
            options={
                "unique_together": {("candidate", "requirement")},
            },
        ),
    ]
