# Generated by Django 5.0.6 on 2026-05-07 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membershipplan",
            name="name_ar",
        ),
    ]
