# Generated by Django 5.0.6 on 2026-06-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="currency",
            field=models.CharField(
                choices=[
                    ("JOD", "دينار أردني (JOD)"),
                    ("SAR", "ريال سعودي (SAR)"),
                    ("AED", "درهم إماراتي (AED)"),
                    ("KWD", "دينار كويتي (KWD)"),
                    ("BHD", "دينار بحريني (BHD)"),
                    ("OMR", "ريال عماني (OMR)"),
                    ("QAR", "ريال قطري (QAR)"),
                    ("EGP", "جنيه مصري (EGP)"),
                    ("USD", "دولار أمريكي (USD)"),
                ],
                default="JOD",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="membershipplan",
            name="currency",
            field=models.CharField(
                choices=[
                    ("JOD", "دينار أردني (JOD)"),
                    ("SAR", "ريال سعودي (SAR)"),
                    ("AED", "درهم إماراتي (AED)"),
                    ("KWD", "دينار كويتي (KWD)"),
                    ("BHD", "دينار بحريني (BHD)"),
                    ("OMR", "ريال عماني (OMR)"),
                    ("QAR", "ريال قطري (QAR)"),
                    ("EGP", "جنيه مصري (EGP)"),
                    ("USD", "دولار أمريكي (USD)"),
                ],
                default="JOD",
                max_length=3,
            ),
        ),
    ]
