# Generated by Django 5.0.6 on 2026-05-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_remove_membershipplan_name_ar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="currency",
            field=models.CharField(default="JOD", max_length=3),
        ),
        migrations.AlterField(
            model_name="membershipplan",
            name="currency",
            field=models.CharField(default="JOD", max_length=3),
        ),
    ]
