# Generated by Django 5.0.6 on 2026-05-07 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_alter_invoice_currency_alter_membershipplan_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="membership",
            name="approved_by_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="membership",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                    ("paused", "Paused"),
                    ("pending", "Pending Payment"),
                    ("pending_approval", "Pending Approval"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
