# Generated by Django 5.0.6 on 2026-05-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_membership_approval_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="paid_by_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
