# Generated by Django 5.0.6 on 2026-07-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_order_buyer_email_order_buyer_name_order_buyer_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productoption",
            name="min_stock_threshold",
            field=models.PositiveIntegerField(default=3),
        ),
    ]
