# Generated by Django 5.0.6 on 2026-05-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="primary_location_id",
        ),
        migrations.AddField(
            model_name="user",
            name="assigned_location_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("platform_admin", "Platform Admin"),
                    ("tenant_owner", "Tenant Owner"),
                    ("manager", "Manager"),
                    ("branch_manager", "Branch Manager"),
                    ("front_desk", "Front Desk"),
                    ("instructor", "Instructor"),
                    ("finance", "Finance"),
                    ("staff", "Staff"),
                    ("parent", "Parent"),
                    ("student", "Student"),
                    ("read_only", "Read Only Auditor"),
                ],
                default="student",
                max_length=30,
            ),
        ),
    ]
