# Generated by Django 5.0.6 on 2026-06-04 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="force_password_reset",
            field=models.BooleanField(
                default=False,
                help_text="When True, user must reset password on next login.",
            ),
        ),
    ]
