# Generated by Django 5.0.6 on 2026-04-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_migrate_name_fields_to_unified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="first_name_ar",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name_ar",
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=100),
        ),
    ]
