# Generated by Django 5.0.6 on 2026-04-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0005_remove_user_first_name_ar_remove_user_last_name_ar_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_initial_password_set",
            field=models.BooleanField(default=True),
        ),
    ]
