# Generated by Django 5.0.6 on 2026-04-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Approval"),
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="subscription_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
