# Generated by Django 5.0.6 on 2026-04-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_tenant_status_tenant_subscription_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="features",
            field=models.JSONField(
                default=dict,
                help_text='يجب إدخال نص JSON صالح. مثال: {"whatsapp": true, "kiosk": true}',
            ),
        ),
    ]
