# Generated by Django 5.0.6 on 2026-06-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_subscriptionchangerequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Approval"),
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("expired", "Expired"),
                    ("trial", "Trial Period"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
