# Generated by Django 5.0.6 on 2026-05-07 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_platformsettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenant",
            name="primary_color",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="secondary_color",
        ),
    ]
