# Generated by Django 5.0.6 on 2026-04-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_alter_plan_features"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalDefaultBelt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("martial_art", models.CharField(default="BJJ", max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("name_ar", models.CharField(blank=True, max_length=100)),
                ("color_hex", models.CharField(default="#FFFFFF", max_length=7)),
                ("order_index", models.PositiveIntegerField(default=0)),
                ("min_attendance_sessions", models.PositiveIntegerField(default=0)),
                ("min_months_since_last", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Global Default Belt",
                "verbose_name_plural": "Global Default Belts",
                "ordering": ["martial_art", "order_index"],
            },
        ),
    ]
