# Generated by Django 5.0.6 on 2026-06-24 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_alter_tenant_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenant",
            name="favicon",
        ),
    ]
