# Generated by Django 5.0.6 on 2026-06-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0005_alter_plan_currency_alter_tenant_default_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantsubscription",
            name="billing_cycle",
            field=models.CharField(
                choices=[
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                    ("biennial", "Biennial"),
                ],
                default="monthly",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="subscriptionchangerequest",
            name="billing_cycle",
            field=models.CharField(
                choices=[
                    ("monthly", "Monthly"),
                    ("yearly", "Yearly"),
                    ("biennial", "Biennial"),
                ],
                default="monthly",
                help_text="دورة الفوترة المطلوبة",
                max_length=20,
            ),
        ),
    ]
