# Generated by Django 5.0.6 on 2026-07-02 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
        ("tenants", "0007_seed_jordanian_default_belts"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GlobalDefaultBelt",
            new_name="Belt",
        ),
        migrations.AlterModelOptions(
            name="belt",
            options={
                "ordering": ["martial_art", "order_index"],
                "verbose_name": "Belt",
                "verbose_name_plural": "Belts",
            },
        ),
    ]
