# Generated by Django 5.0.6 on 2026-07-02 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_rename_globaldefaultbelt_belt_alter_belt_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Belt',
            new_name='GlobalDefaultBelt',
        ),
        migrations.AlterModelOptions(
            name='globaldefaultbelt',
            options={'ordering': ['martial_art', 'order_index'], 'verbose_name': 'Global Default Belt', 'verbose_name_plural': 'Global Default Belts'},
        ),
    ]
