# Generated by Django 5.0.6 on 2026-04-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="manager_id",
        ),
        migrations.AddField(
            model_name="location",
            name="manager_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="student",
            name="assigned_to_id",
        ),
        migrations.AddField(
            model_name="student",
            name="assigned_to_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="student",
            name="created_by_id",
        ),
        migrations.AddField(
            model_name="student",
            name="created_by_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="studentdocument",
            name="uploaded_by_id",
        ),
        migrations.AddField(
            model_name="studentdocument",
            name="uploaded_by_id",
            field=models.UUIDField(),
        ),
        migrations.RemoveField(
            model_name="studentnote",
            name="author_id",
        ),
        migrations.AddField(
            model_name="studentnote",
            name="author_id",
            field=models.UUIDField(),
        ),
    ]
