# Generated by Django 5.0.6 on 2026-05-08 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="name_ar",
        ),
    ]
