# Generated by Django 5.0.6 on 2026-04-25 22:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_alter_location_manager_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="student",
            constraint=models.UniqueConstraint(
                fields=("first_name", "last_name", "phone", "location"),
                name="unique_student_per_branch",
            ),
        ),
    ]
