# Generated by Django 5.0.6 on 2026-04-25 22:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_student_unique_student_per_branch"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="student",
            name="unique_student_per_branch",
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.UniqueConstraint(
                fields=("first_name", "last_name", "phone", "location"),
                name="unique_student_per_branch",
                violation_error_message="هذا الطالب موجود بالفعل في هذا الفرع بنفس البيانات (الاسم ورقم الهاتف).",
            ),
        ),
    ]
