# Generated by Django 5.0.6 on 2026-04-26 19:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_remove_student_unique_student_per_branch_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="student",
            name="unique_student_per_branch",
        ),
        migrations.AlterField(
            model_name="student",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="student",
            name="first_name_ar",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="student",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="student",
            name="last_name_ar",
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.UniqueConstraint(
                fields=("first_name_ar", "last_name_ar", "phone", "location"),
                name="unique_student_per_branch",
                violation_error_message="هذا الطالب موجود بالفعل في هذا الفرع بنفس البيانات (الاسم ورقم الهاتف).",
            ),
        ),
    ]
