# Generated by Django 5.0.6 on 2026-04-26 19:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_migrate_student_name_fields_to_unified"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="student",
            name="unique_student_per_branch",
        ),
        migrations.RemoveField(
            model_name="student",
            name="first_name_ar",
        ),
        migrations.RemoveField(
            model_name="student",
            name="last_name_ar",
        ),
        migrations.AlterField(
            model_name="student",
            name="first_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="student",
            name="last_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name="student",
            constraint=models.UniqueConstraint(
                fields=("first_name", "last_name", "phone", "location"),
                name="unique_student_per_branch",
                violation_error_message="هذا الطالب موجود بالفعل في هذا الفرع بنفس البيانات (الاسم ورقم الهاتف).",
            ),
        ),
    ]
