# Generated by Django 5.0.6 on 2026-05-07 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0001_initial"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="SAR", max_length=3)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("paytabs", "PayTabs"),
                            ("hyperpay", "HyperPay"),
                            ("stripe", "Stripe"),
                            ("cash", "Cash"),
                            ("manual", "Manual Transfer"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "provider_transaction_id",
                    models.CharField(blank=True, max_length=200),
                ),
                ("provider_response", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially Refunded"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("receipt_url", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("processed_by_id", models.UUIDField(blank=True, null=True)),
                (
                    "refund_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("refunded_at", models.DateTimeField(blank=True, null=True)),
                ("refund_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="billing.invoice",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="payments_pa_status_7ad4af_idx"
                    ),
                    models.Index(
                        fields=["student", "status"],
                        name="payments_pa_student_2663d2_idx",
                    ),
                    models.Index(
                        fields=["provider_transaction_id"],
                        name="payments_pa_provide_edad36_idx",
                    ),
                ],
            },
        ),
    ]
